# From
#
# https://chshersh.github.io/posts/2019-02-25-haskell-travis
#
# but slightly adjutsted to deal with the fact that hvega
# (the only component with tests) is in a sub-directory.
#

language: haskell
# dist: bionic
dist: xenial
os: linux

# addons
#   apt:
#     sources:
#       - ppa:hvr/ghc
#     packages:
#     - ghc
#     - cabal

git:
  depth: 5

cabal: "3.2"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

# The stack test takes longer, presumably because of what needs to be
# downloaded, so run this first.
#
jobs:
  include:

  # Stack
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/hvega/stack.yaml"

  # Cabal
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.5
  - ghc: 8.8.3

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      cd $TRAVIS_BUILD_DIR/hvega
      ghc --version
      cabal --version
      cabal v2-update
      cabal v2-build --enable-tests --enable-benchmarks
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --ghc-options=-Werror
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cd $TRAVIS_BUILD_DIR/hvega
      cabal v2-test --enable-tests
    else
      stack test --system-ghc
    fi

notifications:
  email: false
