# From
#
# https://chshersh.github.io/posts/2019-02-25-haskell-travis
#
# but slightly adjutsted to deal with the fact that hvega
# (the only component with tests) is in a sub-directory.
#

sudo: true
language: haskell

# I tried this because of what-turned-out-to-be transient failures
# with Travis (it couldn't download GHC 8.8.1). However, with the
# following change the tests no longer ran, and it's not clear to
# me if that's because there's something wrong below or not, so
# I am removing it for now.
#
# dist: bionic
# addons
#   apt:
#     sources:
#       - ppa:hvr/ghc
#     packages:
#     - ghc
#     - cabal

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

# The stack test takes longer, presumably because of what needs to be
# downloaded, so run this first.
#
matrix:
  include:

  # Stack
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/hvega/stack.yaml"

  # Cabal
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.5
  - ghc: 8.8.3

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      cd $TRAVIS_BUILD_DIR/hvega
      ghc --version
      cabal --version
      cabal new-update
      cabal new-build --enable-tests --enable-benchmarks
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cd $TRAVIS_BUILD_DIR/hvega
      cabal new-test --enable-tests
    else
      stack test --system-ghc
    fi

notifications:
  email: false
