flags: {}

packages:
- .

#extra-deps:
#- aeson-2.0.1.0
#- semialign-1.2
#- time-compat-1.9.6.1
#- hashable-1.3.4.1
#- git: https://github.com/hasufell/aeson-pretty
#  commit: e902ab866bb41d990b66af3644aeb352ff7aaf6f

extra-deps: []

resolver: lts-18.18
